version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "start prebuild and end it"

  build:
    commands:
      - echo "Running Builds..."

  post_build:
    commands:
      - echo "Build completed successfully "



artifacts:
  files:
    - '**/*'
  base-directory: .
